const contNames = {
  BE: 'Belgium',
  BG: 'Bulgaria',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  DE: 'Germany',
  EE: 'Estonia',
  IE: 'Ireland',
  EL: 'Greece',
  ES: 'Spain',
  FR: 'France',
  HR: 'Croatia',
  IT: 'Italy',
  CY: 'Cyprus',
  LV: 'Latvia',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  HU: 'Hungary',
  MT: 'Malt',
  NL: 'Netherlands',
  AT: 'Austria',
  PL: 'Poland',
  PT: 'Portugal',
  RO: 'Romania',
  SI: 'Slovenia',
  SK: 'Slovakia',
  FI: 'Finland',
  SE: 'Sweden',
};

export default contNames;
